Smart reader interface added
Kicer86/RemoteDiscHealthMonitor pull request #5
Opened 2020-10-11 11:13 UTC by wkucjas

2020-10-11 11:14 UTC, wkucjas commented
How to avoid adding these two merge pull requests?

2020-10-11 17:09 UTC, Kicer86 commented on src/agent/SmartReader.h
> +	std::unique_ptr<SmartReader> GetProperSMARTReader();
I believe, this should be a method in a SMARTReadersFactory or something similar.

2020-10-11 17:09 UTC, Kicer86 commented on src/agent/SmartReader.h
> +class SmartReader
This should be an interface being returned from factory

2020-10-11 17:10 UTC, Kicer86 commented on src/agent/SmartReader.h
> +	virtual std::string ReadSMARTData();
pure virtual

2020-10-11 17:11 UTC, Kicer86 requested changes
Prepare factory and interface form SMART Reader

2020-10-12 14:59 UTC, wkucjas commented
Changes added.

2020-10-12 20:25 UTC, Kicer86 commented on src/agent/LinuxSmartReader.h
> +#pragma once
double pragma

2020-10-12 20:26 UTC, Kicer86 commented on src/agent/SmartReader.h
> +class SmartReader
Interfaces usually start with "I" in names

2020-10-12 20:26 UTC, Kicer86 commented on src/agent/WindowsSmartReader.h
> +	std::string ReadSMARTData();
mark with override

2020-10-12 20:26 UTC, Kicer86 commented on src/agent/LinuxSmartReader.h
> +	std::string ReadSMARTData();
mark with override

2020-10-12 20:27 UTC, Kicer86 requested changes
some minor improvements required

2020-10-13 16:56 UTC, wkucjas commented
Done.

2020-10-13 18:55 UTC, Kicer86 approved these changes

2020-10-13 18:55 UTC, merged