Deleting agents
Kicer86/RemoteDiscHealthMonitor pull request #53
Opened 2021-01-30 14:36 UTC by Kicer86

2021-02-11 22:00 UTC, wkucjas requested changes

2021-02-11 22:00 UTC, wkucjas commented on src/monitor/AgentsList.cpp
> +void AgentsList::removeAgentAt(int position)
Could be const int&

2021-02-12 07:28 UTC, Kicer86 commented on src/monitor/AgentsList.cpp
> +void AgentsList::removeAgentAt(int position)
https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rf-in

2021-02-14 17:43 UTC, wkucjas approved these changes

2021-02-14 17:43 UTC, merged